# @package _global_
# デフォルトオプティマイザ設定（AdamW）

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true  # LightningModuleで実際のパラメータを渡すため

  lr: 2.0e-4
  betas: [0.9, 0.95]
  eps: 1.0e-8
  weight_decay: 0.1
