# @package _global_
# 6Mパラメータモデル設定（デバッグ・高速実験用）

model:
  _target_: src.models.lightning_module.DiffusionLMLightningModule

  model_config:
    name: "Llama-6M"
    block_size: 2048
    vocab_size: 32000
    n_layer: 4
    n_head: 4
    n_embd: 256
    rotary_percentage: 1.0
    parallel_residual: false
    bias: false
    norm_class_name: "FusedRMSNorm"
    norm_eps: 1.0e-5
    mlp_class_name: "LLaMAMLP"
    intermediate_size: 688
    condense_ratio: 1

  num_parameters: 6.294784e6  # 約6M

training:
  model_params: ${model.num_parameters}
